[theme]
theme = "gruvbox-dark"
# name = "plain"
# [theme.overrides]
# separator = "|"

[icons]
icons = "awesome6"

[[block]]
block = "focused_window"
format = " $title.str(max_w:25)| "
# show_marks = "visible"


[[block]]
block = "time"
interval = 1
# format = "%a %b/%d %R %P"
format = " $icon $timestamp.datetime(f:'%a %b/%d %R %P') "

[[block]]
block = "temperature"
interval = 5 
# format = "{average}"
format = " $icon $average"
format_alt = " $icon "

[[block]]
block = "sound"
driver = "auto"

[[block]]
block = "external_ip"
format = " \uf3c5 $region_code $ip "
